server:
  port: 1234
  servlet:
    context-path: /reviewapp


myapp:
  value: "Doing Work"
spring:
  datasource:
    username: jamisonm
    password: Randomdogpark
    url: jdbc:postgresql://projects.cpsckzoukykn.us-east-2.rds.amazonaws.com:5432/review_app
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE